### ISSUE TITLE
Decide on how to handle heroku downgrade/https issue

### ISSUE THREAD

**Issue by mei-li** [mei-li/tsougkrizo#27]
In Heroku we are paying 7$ per month. Downgrading to the free tier means that https will not work for the tsougkrizo domain.

One possibilty is to redirect from tsougkrizo.com to https://tsougkrizo.herokuapp.com were the https will keep working.

@FotisK what are the minimum income possibilities from ads for cost coverage?

**Comment by mei-li** [comment]
Now GoDaddy points to our static github page in the `docs` directory that has the page @ManosMav made !

Check it out now
https://www.tsougkrizo.com/ !

**Comment by FotisK** [comment]
Well done, it's working!
